siteTitle: Olaf Klein
siteDescription: Portfolio of Olaf Klein - monkeytower internet agency
footerText: All rights reserved.
socialLinks:
  - label: Facebook
    url: https://www.facebook.com/monkeytower
    icon: facebook
  - label: YouTube
    url: https://www.youtube.com/OlafKlein
    icon: youtube
  - label: Instagram
    url: https://www.instagram.com/olaf_klein_monkeytower/
    icon: instagram
  - label: GitHub
    url: https://github.com/monkeytower
    icon: github
  - label: Twitter
    url: https://twitter.com/monkeytower
    icon: twitter
